server:
  port: 7070
  servlet:
    session:
      cookie:
        name: OAUTH2-PROVIDER-SESSID

management:
  endpoints:
    web:
      exposure:
        include:
        - beans
    
    
logging:
  level:
    #org.springframework.jdbc: debug
    org.springframework.security.oauth2: debug
    #io.lettuce.core: debug

---
spring:
  profile: hsql
  datasource:
    platform: hsql
    url: jdbc:hsqldb:mem:.
    username: SA
    password: 
    initialization-mode: always

  session:
    store-type: none    
    redis:    
      namespace: OAUTH2-PROVIDER    

---
spring:
  profiles: mysql
  datasource:
    platform: mysql
    url: jdbc:mysql://mysql:3306/mysql-db?userSSL=false
    username: root
    password: password
    initialization-mode: always

  redis:
    host: redis
    port: 6379

  session:
    store-type: redis    
    redis:    
      namespace: OAUTH2-PROVIDER